# Array Indexing
Array indexing in NumPy refers to accessing elements or subsets of arrays using indices, slices, or conditions. Below, I’ll explain indexing for arrays of different dimensions, keeping it concise and including examples based on our prior discussion of 0-D, 1-D, 2-D, 3-D, and higher-dimensional arrays.

In [2]:
import numpy as np

## 0-D Array Indexing
A 0-D array (scalar) contains a single element and has no axes to index. You access its value directly.

In [6]:
arr = np.array(42)
print(arr)

42


## 1-D Array Indexing
A 1-D array is like a list. Use a single index to access an element (zero-based indexing) or slices for subsets.

In [9]:
array_1d = np.array([1, 2, 3, 4])
print(array_1d[0])      # 1 (first element)
print(array_1d[1:3])    # [2 3] (slice from index 1 to 2)
print(array_1d[-1])     # 4 (last element)

1
[2 3]
4


## 2-D Array Indexing
A 2-D array (matrix) requires two indices: [row, column]. Use slices for ranges or individual indices for specific elements.

In [12]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d[0, 1])   # 2 (row 0, column 1)
print(array_2d[1, :])   # [4 5 6] (all columns in row 1)
print(array_2d[:, 2])   # [3 6] (all rows in column 2)

2
[4 5 6]
[3 6]


## 3-D Array Indexing
A 3-D array uses three indices: [depth, row, column]. Each index can be a single value or slice.

In [15]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d[0, 1, 1])  # 4 (depth 0, row 1, column 1)
print(array_3d[1, :, :])  # [[5 6] [7 8]] (all rows and columns in depth 1)

4
[[5 6]
 [7 8]]


## Higher-Dimensional Array Indexing
For arrays with more than three dimensions, indexing extends with additional comma-separated indices, one per dimension. For example, a 4-D array uses [dim1, dim2, dim3, dim4]. Slicing and integer indexing work similarly.

In [18]:
array_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
print(array_4d[0, 0, 1, 1])  # 4 (access specific element)
print(array_4d[0, :, :, 0])  # [[1 3] [5 7]] (slice across dimensions)

4
[[1 3]
 [5 7]]
