# Array Slicing
NumPy array slicing allows extracting subsets of arrays using index ranges or conditions across dimensions. Below, I’ll explain slicing for arrays of different dimensions (building on our prior discussion of 0-D, 1-D, 2-D, 3-D, and higher-dimensional arrays) with concise explanations and examples. Slicing syntax is [start:end:step], where start, end, and step are optional, and indices are zero-based.

In [3]:
import numpy as np

## 0-D Array Slicing
A 0-D array (scalar) has no dimensions to slice, so slicing isn’t applicable. You access the single value directly.

In [5]:
arr = np.array(42)
print(arr)

42


## 1-D Array Slicing
A 1-D array is sliced using a single range [start:end:step]. Omitting start or end implies the beginning or end of the array.

In [8]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d[1:4])      # [2 3 4] (elements from index 1 to 3)
print(array_1d[:3])       # [1 2 3] (start to index 2)
print(array_1d[::2])      # [1 3 5] (every second element)
print(array_1d[-2:])      # [4 5] (last two elements)

[2 3 4]
[1 2 3]
[1 3 5]
[4 5]


## 2-D Array Slicing
A 2-D array uses two ranges: [row_start:row_end:row_step, col_start:col_end:col_step]. Each dimension is sliced independently.

In [11]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d[0:2, 1:3])  # [[2 3] [5 6]] (rows 0-1, columns 1-2)
print(array_2d[:, 1])      # [2 5 8] (all rows, column 1)
print(array_2d[::2, :])    # [[1 2 3] [7 8 9]] (every second row)

[[2 3]
 [5 6]]
[2 5 8]
[[1 2 3]
 [7 8 9]]


## 3-D Array Slicing
A 3-D array uses three ranges: [depth_start:depth_end:depth_step, row_start:row_end:row_step, col_start:col_end:col_step].

In [14]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d[0, :, :])     # [[1 2] [3 4]] (all rows and columns in depth 0)
print(array_3d[:, 1, 0])     # [3 7] (all depths, row 1, column 0)
print(array_3d[0:2, 0:1, :]) # [[[1 2]] [[5 6]]] (depth 0-1, row 0, all columns)

[[1 2]
 [3 4]]
[3 7]
[[[1 2]]

 [[5 6]]]


## Additional Slicing Techniques
Negative Indices: Use negative values to slice from the end (e.g., -2: for the last two elements).

Step: Controls the interval (e.g., ::2 for every second element).

Boolean Slicing: Use conditions for filtering. Example: array_1d[array_1d > 3] returns [4, 5].

Ellipsis (...): Represents all remaining dimensions. Example: array_4d[..., 1] slices the last dimension.

## Notes
Slices return views, not copies, so modifying a slice modifies the original array.
    
Out-of-bounds slices are handled gracefully (e.g., array_1d[10:15] returns an empty array if indices exceed bounds).
                                             
Default values: start=0, end=length, step=1.