# Array Copy vs View

In NumPy, understanding the difference between a copy and a view of an array is crucial for managing data efficiently and avoiding unintended modifications. Below, I’ll explain the concepts concisely, tying them to our prior discussions on NumPy arrays (0-D, 1-D, 2-D, 3-D, and higher-dimensional arrays), with examples for clarity.

### View
A view is a new array object that refers to the same data as the original array (shallow copy).

Modifying the view modifies the original array, and vice versa, as they share the same memory.
    
Operations like slicing, indexing, or reshaping often create views.

Memory Efficiency: Views don’t duplicate data, saving memory.

Check: Use array.base to see if an array is a view (None for originals/copies, original array for views).
                                                    
### Copy
A copy is a new array with independent data (deep copy).
    
Modifying a copy does not affect the original array, and vice versa.
    
Created explicitly using copy() or operations that inherently duplicate data.
    
Memory Usage: Copies consume additional memory since data is duplicated.
    

In [5]:
import numpy as np

## 0-D Array
0-D arrays (scalars) don’t support slicing, so views are less relevant. Copies are straightforward.

In [7]:
arr = np.array(42)
arr_copy = arr.copy()
arr_copy = 99
print(arr)   
print(arr_copy)

42
99


## 1-D Array
Slicing creates a view; copy() creates a copy.

In [12]:
arr1 = np.array([1, 2, 3, 4])
view_1d = arr1[1:3]  # View
copy_1d = arr1[1:3].copy()  # Copy
view_1d[0] = 99
print(arr1)     
print(view_1d)      
print(copy_1d)      
print(view_1d.base is arr1)

[ 1 99  3  4]
[99  3]
[2 3]
True


## 2-D Array
Slicing or reshaping creates views; copy() ensures independent data.

In [15]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
view_2d = arr2[:, 1:3]  # View
copy_2d = arr2[:, 1:3].copy()  # Copy
view_2d[0, 0] = 99
print(arr2)     
print(view_2d)      
print(copy_2d)

[[ 1 99  3]
 [ 4  5  6]]
[[99  3]
 [ 5  6]]
[[2 3]
 [5 6]]


## 3-D Array
Views and copies work similarly, with views sharing data across all dimensions.

In [18]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
view_3d = arr3[0, :, :]  # View
copy_3d = arr3[0, :, :].copy()  # Copy
view_3d[0, 0] = 99
print(arr3)    
print(view_3d)     
print(copy_3d)

[[[99  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]]
[[99  2]
 [ 3  4]]
[[1 2]
 [3 4]]


## Higher-Dimensional Arrays
The same principles apply: slicing creates views, copy() creates independent arrays.

In [21]:
arr4 = np.array([[[[1, 2], [3, 4]]]])
view_4d = arr4[:, :, :, 0]  # View
copy_4d = arr4[:, :, :, 0].copy()  # Copy
view_4d[0, 0, 0] = 99
print(arr4) 
print(view_4d)      
print(copy_4d)

[[[[99  2]
   [ 3  4]]]]
[[[99  3]]]
[[[1 3]]]
