In [1]:
import numpy as np

## Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

## 0-D Arrays
A 0-D array, or scalar, is a single data element in NumPy, lacking dimensions, representing a single value.

In [4]:
arr = np.array(42)
arr

array(42)

## 1-D Arrays
A 1-D array in NumPy is a linear sequence of elements, like a list, with one dimension, storing multiple values.

In [6]:
arr1 = np.array([1, 2, 3, 4])
print(arr1)

[1 2 3 4]


## 2-D Arrays
A 2-D array in NumPy is a matrix-like structure with rows and columns, having two dimensions, storing tabular data.

In [8]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


## 3-D Arrays
A 3-D array in NumPy is a multi-layered matrix, with three dimensions, organizing data in a cube-like structure.

In [10]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Check Number of Dimensions?
To check the number of dimensions in a NumPy array, use the .ndim attribute, which returns the array's dimensionality.

In [12]:
print('number of dimensions :', arr.ndim)
print('number of dimensions :', arr1.ndim)
print('number of dimensions :', arr2.ndim)
print('number of dimensions :', arr3.ndim)

number of dimensions : 0
number of dimensions : 1
number of dimensions : 2
number of dimensions : 3


## Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [14]:
arr4 = np.array([1, 2, 3, 4], ndmin=5)

print(arr4)
print('number of dimensions :', arr4.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
