# Filter Array
n NumPy, array filtering extracts elements or subarrays based on conditions, typically using boolean indexing or functions like np.where. This builds on our prior discussions of array shapes, indexing, slicing, joining, splitting, searching, sorting, and iteration for 0-D, 1-D, 2-D, 3-D, and higher-dimensional arrays. Below, I’ll explain filtering concisely with examples across these array types, focusing on boolean indexing and np.where for creating filtered arrays.

## Key Points
Boolean Indexing: Use a boolean array (True/False) of the same shape to select elements where True.

np.where: Returns indices of elements meeting a condition or selects values based on the condition.
    
Filtering creates a copy of the selected elements, not a view, unless slicing is involved.

Conditions can involve comparisons (e.g., >, <, ==) or logical operations (&, |, ~).
### Filtering Across Array Dimensions

In [2]:
import numpy as np

## 0-D Array (Scalar)
A 0-D array has one element, so filtering is trivial—check the value directly.

In [ ]:
scalar = np.array(42)
filtered = scalar[np.array([scalar > 40])]  # Boolean condition
print(filtered)

## 1-D Array
Filter elements using a boolean array or np.where to select values based on a condition.

In [8]:
# Boolean Indexing
array_1d = np.array([1, 2, 3, 4, 5])
condition = array_1d > 2
filtered = array_1d[condition]
print(filtered)

[3 4 5]


In [10]:
# np.where
filtered = array_1d[np.where(array_1d > 2)]
print(filtered)

[3 4 5]


## 2-D Array
Filter elements, rows, or columns using boolean arrays or conditions applied to specific axes.

In [13]:
# Boolean Indexing, Element-wise
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
condition = array_2d % 2 == 0  # Even numbers
filtered = array_2d[condition]
print(filtered)

[2 4 6]


In [15]:
# Filter Rows
condition = array_2d[:, 0] > 2  # Rows where first column > 2
filtered_rows = array_2d[condition]
print(filtered_rows)

[[4 5 6]]


## 3-D Array
Filter elements or subarrays along any axis using boolean conditions.

In [18]:
# Boolean Indexing
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
condition = array_3d > 4
filtered = array_3d[condition]
print(filtered)

[5 6 7 8]


In [20]:
# np.where
indices = np.where(array_3d > 4)
print(indices)  
print(array_3d[indices])

(array([1, 1, 1, 1], dtype=int64), array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))
[5 6 7 8]


## Higher-Dimensional Arrays
Filtering extends similarly, with boolean arrays matching the array’s shape.

In [25]:
# 4-D Array
array_4d = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
condition = array_4d > 4
filtered = array_4d[condition]
print(filtered)

[5 6 7 8]


### Advanced Filtering

##### Multiple Conditions:

In [29]:
array_1d = np.array([1, 2, 3, 4, 5])
condition = (array_1d > 2) & (array_1d < 5)
filtered = array_1d[condition]
print(filtered)

[3 4]


## Logical Operations:
& (and), | (or), ~ (not) combine conditions.

Example: array_1d[(array_1d == 1) | (array_1d == 5)] yields [1 5].

Filtering with np.where for Conditional Assignment:

In [32]:
array_1d = np.array([1, 2, 3, 4, 5])
result = np.where(array_1d > 3, array_1d, 0)  # Replace elements > 3 with themselves, else 0
print(result)

[0 0 0 4 5]


##### String Arrays:

In [35]:
array_str = np.array(['apple', 'banana', 'cherry'])
filtered = array_str[array_str == 'apple']
print(filtered)

['apple']


## Key Notes
Performance: Boolean indexing and np.where are vectorized, making them efficient for large arrays compared to loops.

Copies vs. Views: Filtering with boolean indexing or np.where creates a copy of the selected elements, not a view.

Shape: Filtered results may be flattened (e.g., element-wise filtering) or retain shape (e.g., row filtering).

NaN Handling:

In [38]:
array_1d = np.array([1, np.nan, 3])
filtered = array_1d[~np.isnan(array_1d)]
print(filtered)

[1. 3.]


Empty Results: If no elements meet the condition, an empty array is returned.