# Joining Array

In NumPy, joining arrays combines multiple arrays into a single array using functions like concatenate, stack, hstack, vstack, dstack, or block. This builds on our prior discussions of array shapes, indexing, slicing, and iteration for 0-D, 1-D, 2-D, 3-D, and higher-dimensional arrays. Below, I’ll explain key joining methods concisely with examples across these array types, ensuring compatibility with shapes and dimensions.

### Key Points
Arrays must have compatible shapes for joining (e.g., same dimensions except along the joining axis).
                                  
Joining operations typically create a new array (copy), not a view.
                                  
The joining method determines how arrays are combined (e.g., along rows, columns, or depth).

Use axis to specify the dimension for joining (default: axis=0).
### Joining Methods
np.concatenate: Joins arrays along an existing axis.
    
np.stack: Joins arrays along a new axis, increasing dimensionality.

np.hstack: Stacks arrays horizontally (column-wise, along axis 1).
                                       
np.vstack: Stacks arrays vertically (row-wise, along axis 0).
                                     
np.dstack: Stacks arrays depth-wise (along axis 2).
                                     
np.block: Constructs arrays from nested lists of arrays.

### Joining Across Array Dimensions

## 0-D Array (Scalar)
0-D arrays (scalars) cannot be joined directly due to their lack of dimensions. Convert to 1-D first.

In [5]:
import numpy as np
aar = np.array(42)
aar1 = np.array(99)
array_1d = np.concatenate([np.array([aar]), np.array([aar1])])
print(array_1d)

[42 99]


## 1-D Array
1-D arrays can be joined along their single axis (axis=0) or stacked to form higher dimensions.

In [8]:
# Concatenate
array_1d_1 = np.array([1, 2])
array_1d_2 = np.array([3, 4])
joined = np.concatenate((array_1d_1, array_1d_2))  # Along axis 0
print(joined)

[1 2 3 4]


In [10]:
# Stack
stacked = np.stack((array_1d_1, array_1d_2))  # New axis (2-D)
print(stacked) 
print(stacked.shape)

[[1 2]
 [3 4]]
(2, 2)


## 2-D Array
2-D arrays can be joined along axis=0 (rows) or axis=1 (columns), or stacked to form 3-D arrays.

In [13]:
# Concatenate along axis=0
array_2d_1 = np.array([[1, 2], [3, 4]])
array_2d_2 = np.array([[5, 6], [7, 8]])
joined_rows = np.concatenate((array_2d_1, array_2d_2), axis=0)
print(joined_rows) 
print(joined_rows.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [15]:
# hstack
hstacked = np.hstack((array_2d_1, array_2d_2))  # Along axis 1 (columns)
print(hstacked)
print(hstacked.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


In [17]:
# vstack
vstacked = np.vstack((array_2d_1, array_2d_2))  # Along axis 0 (rows)
print(vstacked)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 3-D Array
3-D arrays can be joined along axis=0 (depth), axis=1 (rows), or axis=2 (columns), or stacked to form 4-D arrays.

In [20]:
# Concatenate along axis=0
array_3d_1 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d_2 = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
joined = np.concatenate((array_3d_1, array_3d_2), axis=0)
print(joined.shape) 
print(joined)

(4, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]


In [22]:
# dstack
dstacked = np.dstack((array_3d_1, array_3d_2))  # Along axis 2 (depth)
print(dstacked.shape) 
print(dstacked)

(2, 2, 4)
[[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


## Higher-Dimensional Arrays
Higher-dimensional arrays follow the same principles, joining along any compatible axis or stacking to add a new dimension.

In [25]:
# 4-D Array
array_4d_1 = np.array([[[[1, 2], [3, 4]]]])
array_4d_2 = np.array([[[[5, 6], [7, 8]]]])
joined = np.concatenate((array_4d_1, array_4d_2), axis=0)
print(joined.shape) 
stacked = np.stack((array_4d_1, array_4d_2), axis=1)  # New axis
print(stacked.shape)

(2, 1, 2, 2)
(1, 2, 1, 2, 2)


## Key Notes
Shape Compatibility: Arrays must have the same shape except along the joining axis (e.g., for axis=0, all other dimensions must match).