# Array Reshape
In NumPy, reshaping changes an array’s shape (dimensions) without altering its data, provided the total number of elements remains the same. The reshape() method or np.reshape() function is used to reorganize the array’s structure. This builds on our prior discussion of array shapes, indexing, slicing, and copy vs. view for 0-D, 1-D, 2-D, 3-D, and higher-dimensional arrays. Below, I’ll explain reshaping with concise examples across these array types.
## Key Points
Reshape Requirement: The product of the new shape’s dimensions must equal the total number of elements in the original array.

View vs. Copy: reshape() typically creates a view (shares memory with the original). Use copy() for an independent array.

Syntax: array.reshape(new_shape) or np.reshape(array, new_shape), where new_shape is a tuple or integers.

Flattening: Reshape to 1-D using reshape(-1) or flatten()/ravel() (latter may return a view).

## Reshaping Across Array Dimensions

In [4]:
import numpy as np

## 0-D Array
A 0-D array (scalar) has one element and cannot be reshaped since it lacks dimensions to reorganize.

In [7]:
arr = np.array(42)
# aar.reshape(1, 1)  # Error: cannot reshape array of size 1 into any other shape
print(arr.shape)

()


## 1-D Array
A 1-D array can be reshaped into compatible higher dimensions (e.g., 2-D, 3-D) if the total number of elements matches.

In [10]:
arr1 = np.array([1, 2, 3, 4])
arr2 = arr1.reshape(2, 2) 
print(arr2)      
print(arr2.shape) 
arr1[0] = 99      
print(arr2)

[[1 2]
 [3 4]]
(2, 2)
[[99  2]
 [ 3  4]]


## 2-D Array
A 2-D array can be reshaped to 1-D, another 2-D shape, or higher dimensions, as long as the element count is preserved.

In [13]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr1 = arr2.reshape(-1)  
print(arr1)       
arr3 = arr2.reshape(2, 1, 3)  
print(arr3)       
print(arr3.shape)

[1 2 3 4 5 6]
[[[1 2 3]]

 [[4 5 6]]]
(2, 1, 3)


## 3-D Array
A 3-D array can be reshaped into 1-D, 2-D, or another 3-D shape, or higher dimensions, maintaining the total element count.

In [16]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr2 = arr3.reshape(2, 4)  
print(arr2)       
arr1 = arr3.reshape(-1)  
print(arr1)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


## Higher-Dimensional Arrays
Higher-dimensional arrays follow the same logic: reshape into any compatible shape with the same total number of elements.

In [19]:
arr4 = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
print(arr4.shape)  
arr2 = arr4.reshape(4, 2)  
print(arr2)       
arr3 = arr4.reshape(2, 2, 2) 
print(arr3)

(1, 2, 2, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Additional Notes
Invalid Shapes: Reshaping fails if the new shape’s element count doesn’t match (e.g., reshaping (2, 3) to (2, 4) raises an error).

In [ ]:
array_2d.reshape(2, 4)  # Error: cannot reshape array of size 6 into shape (2, 4)