# Searching Arrays
In NumPy, array search operations locate elements or their indices based on specific conditions or values. This builds on our prior discussions of array shapes, indexing, slicing, joining, splitting, and iteration for 0-D, 1-D, 2-D, 3-D, and higher-dimensional arrays. Below, I’ll explain key search methods (where, argmax, argmin, searchsorted, nonzero, argwhere) concisely with examples across these array types, ensuring compatibility with shapes and dimensions. These methods are optimized for performance on large arrays.
### Key Search Methods
np.where(condition[, x, y]): Returns indices where condition is True or selects elements from x or y based on condition.
np.argmax: Returns the index of the maximum value (optionally along an axis).
np.nanargmax: Like argmax, but ignores NaN values.
np.argmin / np.nanargmin: Returns the index of the minimum value, with nanargmin ignoring NaN.
np.searchsorted: Performs binary search on a sorted array to find where a value would be inserted.
np.nonzero: Returns indices of non-zero elements.
np.argwhere: Returns indices of elements satisfying a condition, grouped by element.
### Search Across Array Dimensions

In [2]:
import numpy as np

## 0-D Array (Scalar)
A 0-D array has one element, so searching is trivial—check the value directly.

In [5]:
scalar = np.array(42)
result = np.where(scalar == 42)
print(result)

(array([0], dtype=int64),)


C:\Users\vigla\AppData\Local\Temp\ipykernel_19260\2616341987.py:2: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  result = np.where(scalar == 42)


## 1-D Array
Search for indices of specific values or conditions, returning a tuple of indices.

In [8]:
array_1d = np.array([1, 2, 3, 4, 2])
result = np.where(array_1d == 2)
print(result)

(array([1, 4], dtype=int64),)


In [10]:
# argmax/argmin
print(np.argmax(array_1d))
print(np.argmin(array_1d))

3
0


In [14]:
# searchsorted
sorted_array = np.array([1, 2, 3, 4])
print(np.searchsorted(sorted_array, 3))

2


## 2-D Array
Search along axes or element-wise, returning indices as tuples (row, column).

In [19]:
array_2d = np.array([[1, 2, 3], [4, 5, 2]])
result = np.where(array_2d == 2)
print(result)
print(list(zip(result[0], result[1])))

(array([0, 1], dtype=int64), array([1, 2], dtype=int64))
[(0, 1), (1, 2)]


In [21]:
# argmax along axis
print(np.argmax(array_2d, axis=1))

[2 1]


## 3-D Array
Search returns indices as tuples (depth, row, column) or along specific axes.

In [24]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 2], [7, 8]]])
result = np.where(array_3d == 2)
print(result)

(array([0, 1], dtype=int64), array([0, 0], dtype=int64), array([1, 1], dtype=int64))


In [26]:
# nonzero
print(np.nonzero(array_3d))

(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64), array([0, 0, 1, 1, 0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))


## Higher-Dimensional Arrays
Search extends similarly, with indices for each dimension.

4-D Array with argwhere

In [30]:
array_4d = np.array([[[[1, 2], [3, 4]], [[5, 2], [7, 8]]]])
result = np.argwhere(array_4d == 2)
print(result)

[[0 0 0 1]
 [0 1 0 1]]


## Advanced Search Features

##### NaN Handling:

In [34]:
array_1d = np.array([1, np.nan, 3, 4])
print(np.nanargmax(array_1d))

3


##### Multiple Values (searchsorted)

In [37]:
sorted_array = np.array([1, 2, 3, 4])
print(np.searchsorted(sorted_array, [2, 5]))

[1 4]


In [ ]:
####Boolean Conditions