# Sorting Arrays
In NumPy, array sorting arranges elements in a specified order (ascending or descending) using functions like np.sort, np.argsort, np.partition, or methods like array.sort(). This builds on our prior discussions of array shapes, indexing, slicing, joining, splitting, searching, and iteration for 0-D, 1-D, 2-D, 3-D, and higher-dimensional arrays. Below, I’ll explain key sorting methods concisely with examples across these array types, focusing on sorting along axes and handling different data types.

### Key Sorting Methods
np.sort(array, axis=-1, kind='quicksort'): Returns a sorted copy of the array.
    
array.sort(axis=-1): Sorts the array in-place (modifies original).

np.argsort(array, axis=-1): Returns indices that would sort the array.
    
np.partition(array, kth, axis=-1): Partially sorts, placing kth smallest/largest elements in position.

np.lexsort(keys): Sorts by multiple keys (e.g., sort by one column, then another).

### Key Parameters
axis: Specifies dimension to sort (default: -1, last axis). Use None to flatten and sort.

kind: Sorting algorithm ('quicksort', 'mergesort', 'heapsort', 'stable'; default: 'quicksort').

order: For structured arrays, sorts by specified field(s).

#### Sorting Across Array Dimensions

## 0-D Array (Scalar)
A 0-D array has one element, so sorting is not applicable.

In [ ]:
import numpy as np
scalar = np.array(42)
print(np.sort(scalar))

## 1-D Array
Sorts elements in ascending order by default, or returns indices with argsort.

In [7]:
array_1d = np.array([3, 1, 4, 2])
sorted_array = np.sort(array_1d)
print(sorted_array) 
print(array_1d)

[1 2 3 4]
[3 1 4 2]


In [9]:
# argsort
indices = np.argsort(array_1d)
print(indices)
print(array_1d[indices])

[1 3 0 2]
[1 2 3 4]


In [11]:
# in-place sort
array_1d.sort()
print(array_1d)

[1 2 3 4]


## 2-D Array
Sort along a specific axis (rows or columns) or flatten for a 1-D sorted array.

In [14]:
# Sort along axis=0, rows
array_2d = np.array([[3, 2, 1], [6, 5, 4]])
sorted_array = np.sort(array_2d, axis=0)
print(sorted_array)

[[3 2 1]
 [6 5 4]]


In [16]:
# Sort along axis=1, columns
sorted_array = np.sort(array_2d, axis=1)
print(sorted_array)

[[1 2 3]
 [4 5 6]]


In [18]:
# Flatten and sort
sorted_flat = np.sort(array_2d, axis=None)
print(sorted_flat)

[1 2 3 4 5 6]


## 3-D Array
Sort along any axis (depth, rows, columns) or flatten.

In [21]:
# Sort along axis=2, columns
array_3d = np.array([[[4, 1], [3, 2]], [[7, 6], [8, 5]]])
sorted_array = np.sort(array_3d, axis=2)
print(sorted_array)

[[[1 4]
  [2 3]]

 [[6 7]
  [5 8]]]


In [23]:
# argsort along axis=1
indices = np.argsort(array_3d, axis=1)
print(indices)

[[[1 0]
  [0 1]]

 [[0 1]
  [1 0]]]


## Higher-Dimensional Arrays
Sorting extends to any axis, with similar behavior.

In [26]:
# 4-D Array
array_4d = np.array([[[[4, 1], [3, 2]], [[7, 6], [8, 5]]]])
sorted_array = np.sort(array_4d, axis=3)
print(sorted_array)

[[[[1 4]
   [2 3]]

  [[6 7]
   [5 8]]]]


### Sorting with Different Data Types

##### Strings:

In [30]:
array_str = np.array(['banana', 'apple', 'cherry'])
print(np.sort(array_str))

['apple' 'banana' 'cherry']


##### Structured Arrays:

In [33]:
dtype = [('name', 'U10'), ('age', int)]
array_struct = np.array([('Alice', 25), ('Bob', 30)], dtype=dtype)
print(np.sort(array_struct, order='age'))

[('Alice', 25) ('Bob', 30)]


### Advanced Sorting
##### Partial Sorting (partition):

In [36]:
array_1d = np.array([3, 1, 4, 2])
print(np.partition(array_1d, 2))

[1 2 3 4]


##### Descending Order: Use [::-1] on sorted array or negate for argsort.

In [41]:
print(np.sort(array_1d)[::-1])

[4 3 2 1]


##### Lexsort (Multi-key sorting):

In [44]:
names = np.array(['Bob', 'Alice', 'Charlie'])
ages = np.array([30, 25, 25])
indices = np.lexsort((names, ages))  # Sort by age, then name
print(names[indices])

['Alice' 'Charlie' 'Bob']


## Key Notes
Performance: NumPy sorting is optimized (O(n log n) for quicksort). Avoid Python’s sorted for large arrays.

Views vs. Copies: np.sort returns a copy; array.sort() modifies in-place; argsort returns indices.

NaN Handling: NaN values are sorted to the end.